NLeSC/guide

- languages/python.md
I find conda far more convenient than virtualenv/pip (it can replace both).
> Updated Python guide with conda info.

- languages/python.md
Added more info for virtualenv and pip, including virtualenvwrapper and wheel. Also tried to nuance the difference between pip/virtualenv and conda. Fixes #3.
> Added more virtualenv and pip info

- languages/fortran.md
Fortran language chapter, mostly done.
> Fortran section

- languages/ccpp.md
Some say it is an introduction, and that it is a literary masterpiece. All we know is that it's called a pull request. Including input by @nielsdrost.
> Add introductory text for C++ chapter

- languages/javascript.md
I wrote some more text on TypeScript from my recent experience with sim-city-cs
> Updated TypeScript section

- languages/javascript.md
right back at you :)!
in this PR:
- deleted some old recommendations/tools/practices
- updated links or deleted them as necessary
- splitted bash sudo apt-get line over multiple lines, so each line can be explained (I added the hashtags but could you fill in the comments in a later commit?)
- I tried to adhere to a one-sentence-per-line in multi-sentence paragraphs, to facilitate easier diffing, as you would in e.g. latex
Thanks for merging,
-Jurriaan
> updated javascript/typescript chapter

- software/code_quality.md
> Fix .editorconfig link.

- software/version_control.md
Projects in own GitHub organization, etc.
> Explain how we use Github at the NLeSC.

- software/code_review.md
Re-read this and improved the wording a bit, and had another look at some of the code review Github plug-ins and updated some information. Nothing major.
> Some code review improvements

- languages/python.md
Daniela and me felt that Anaconda or Miniconda should be recommended when one does not have admin rights.
> Advertising Anaconda

- languages/python.md
> Use the nlesc account for uploading packages to PyPI

- languages/python.md
> Python: Use pytest not nose

- SUMMARY.md
- projects/communication.md
- software/checklist.md
- software/communication.md
I've updated the communication section slightly, and moved the "pitch presentation" item to the projects chapter.
> Communication update

- .gitignore
- .travis.yml
Refs #24 
TODO: At https://travis-ci.org/NLeSC/guide/settings configure Travis-CI to perform cron jobs every week to check links. Build on Push and Pull Request should be disabled
> Added Travis-CI config which runs a broken link checker.

- languages/javascript.md
- languages/python.md
- languages/r.md
- software/code_quality.md
- software/code_review.md
- software/documentation.md
This tackles #69 
It does not fix all of the broken links, just easy cases.
The difficult ones I mentioned in the respective issue.
> Fix easy to fix broken urls

- .travis.yml
- software/code_review.md
Removed dead link, and text stating that.
> Removing and/or excluding Dead links

- languages/opencl-cuda.md
I think the OpenCL and CUDA guide is ready to be merged with master
> Rewrite opencl cuda

- e-infrastructure/e-infrastructure.md
A solution for submitting code to GitHub from a remote machine that provides both safety and convenience.
> Submitting code from a cluster to a GitHub repo

- e-infrastructure/e-infrastructure.md
Changed the format from regular text to code format.
> This command line did not get the correct layout.

- publishing/publishing_results.md
- software/releases.md
- software/testing.md
- software/version_control.md
Also includes minor patches for nightly builds and dois for releases.
> Rewrite of GitHub chapter

- languages/python.md
This is more secure than the old procedure.
> Upload to PyPI using twine

- languages/python.md
Add tools to python chapter: pylint, yapf, isort, venv
> Add tools to python chapter: pylint, yapf, isort, venv

- publishing/publishing_results.md
Hello, and 1k thanks for making your guide a repo :-)
I felt that `Citing` advice could use a link to more the background docu, hence this PR.
Cheers!
> link to official GitHub-Zenodo-integration docu

- languages/r.md
Seting ---> Setting
populage ---> populate
> Fixed minor typos in R language guide

- software/version_control.md
see the commit messages and issue https://github.com/NLeSC/guide/issues/125
> Jspaaks rm copyrighted files

- languages/javascript.md
fixes https://github.com/NLeSC/guide/issues/127
> replaced broken link

- languages/javascript.md
- software/checklist-matrix.md
- software/checklists/checklist-mature.md
- software/releases.md
Travis check was failing due to couple of broken links. This should fix it.
> Fixed PyPi and FountainJs links

- software/code_review.md
We need some better integration with the other parts of this chapter. Any ideas about how to that?
> Add rubric to code review guidelines

- publishing/publishing_results.md
Adding data preservation section, written by @vincentvanhees and [discussed on data-sig](https://github.com/NLeSC/data-sig/issues/15).
> Adding 'Data storage and preservation' section

- SUMMARY.md
- software/checklist-matrix.md
- software/checklist.md
- software/checklists/checklist-mature.md
- software/checklists/checklist-prerelease.md
- software/checklists/checklist-prototype.md
Some time ago @mkuzak had already created this printable versions of the checklist. I've linked them to the `checklist` section so they are actually findable.
> Make printable checklists findable

- languages/ccpp.md
Changes following the C++-anonymous meeting.
> Changes following the C++-anonymous meeting.

- SUMMARY.md
- intellectual_property/intellectual_property_overview.md
- intellectual_property/some_rules.md
PR containing only the parts of PR #81 that everyone agrees on.
> Add some simple rules for common situations (partial)

- SUMMARY.md
- intellectual_property/intellectual_property_overview.md
- intellectual_property/some_rules.md
Fixes #79, and hopefully saves people some time :).
> Add some simple rules for common situations

- best_practices/documentation.md
Updating software citation information.
> Update citation information

- best_practices/language_guides/javascript.md
> fixed broken link aaron-powell blog sourcemaps

- best_practices/language_guides/java.md
> Fix type & wording

- citable_software/publishing_results.md
First version of section about data management plans -- will probably update at a later stage.
> Add some info on data management plans

- citable_software/making_software_citable.md
- added instructions for when the github-zenodo integration does not work as expected
> github-zenodo instructions

- best_practices/language_guides/python.md
Instead of using organization nlesc account.
> Prefer personal uploads to PyPI

- best_practices/language_guides/python.md
> Fix link: python loggin best practices.

- best_practices/language_guides/r.md
Adding **R for Data Science** book recommended by Gerhard Burger via email.
> Update list of R books

- citable_software/conferences_journals_workshops.md
> Add more conferences and update links

- SUMMARY.md
Removing chapter stubs. Should be re-added when the contents for these chapters is written.
> Removing chapter stubs

- citable_software/conferences_journals_workshops.md
> Mention PASC conference

- best_practices/code_quality.md
Fixed typo
- I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).
> Fixed typo in code_quality.md

- CITATION.cff
- CONTRIBUTING.md
Adding `CITATION.cff` to make the guide citable. Data from this file will later be used to add metadata in zenodo.
> Adding CITATION.cff

- best_practices/language_guides/ccpp.md
based on Slack discussion of today:
merijn Yesterday at 14:56
We don't really have any standardisation of how to package C++ code, do we?
29 replies
wrvhage  3 hours ago
Are there any suggestions? Then we can discuss.
wrvhage  3 hours ago
Everbody: As far as I know there’s only (pretty bad) build systems. Correct me if I’m wrong?
egpbos  2 hours ago
that is the cliché, yes :wink:
egpbos  2 hours ago
everything is horrible, and nothing is anyone's own fault :smile:
egpbos  2 hours ago
of course i wholeheartedly agree (edited)
egpbos  2 hours ago
but seriously, it depends a lot on what you're packaging
egpbos  2 hours ago
conda is used more and more for c++ things as well, especially for numerical computing or data science things
egpbos  2 hours ago
the big advantages being that it's cross …
> update package management section

- citable_software/conferences_journals_workshops.md
I added JOSS (Journal of Open Source Software) to the list of journals where people can publish software.
> Adds JOSS to list of journals

- best_practices/language_guides/python.md
Added an I/O section with an item for configuration using either argparse or ConfigArgParse. Using the latter in the Spoken Language project now, really happy with it!
> Python configargparse

- best_practices/language_guides/ccpp.md
These are still very popular on many HPC clusters.
Adds information about Linux environment modules
> Added a small paragraph about environment modules

- best_practices/language_guides/ccpp.md
Added section about clang-format
> Added section about clang-format

- best_practices/language_guides/ccpp.md
Mentioned spack package manager.
> Spack package manger added

- best_practices/language_guides/ccpp.md
> added clang-tidy

- best_practices/testing.md
- best_practices/version_control.md
> Replace Travis with GH Actions + point to turing way

- best_practices/version_control.md
* Link to Turing way in version control chapter
* GitHub private repos are free
> Link to Turing way in version control chapter

- best_practices/language_guides/python.md
- best_practices/language_guides/r.md
- best_practices/releases.md
- best_practices/testing.md
- best_practices/version_control.md
- citable_software/conferences_journals_workshops.md
- nlesc_specific/checklist/checklist_mature.md
- nlesc_specific/checklist/checklist_prerelease.md
- nlesc_specific/checklist/checklist_prototype.md
- nlesc_specific/checklist_matrix.md
- nlesc_specific/projects/end_of_a_project.md
- nlesc_specific/projects/kickoff_meeting.md
- nlesc_specific/projects/new_project.md
- nlesc_specific/projects/project_reviews.md
- Remove all mentions of eStep, closes #228 
- Remove all mentions of Travis, see #211
- Remove mentions of Lode
> Remove all mentions of eStep and Travis

- citable_software/publishing_results.md
> Add 23 Things resources

- best_practices/language_guides/r.md
Old domain got squatted
Correct URL of rapport R template system.
> Update rapport URL

- best_practices/language_guides/ccpp.md
- best_practices/version_control.md
- Fix space before commas found by chance. I only found two occurrences with `grep -r " ,"`.
> Fix commas after spaces

- best_practices/code_review.md
- best_practices/documentation.md
- best_practices/language_guides/ccpp.md
- best_practices/language_guides/javascript.md
- best_practices/language_guides/opencl_cuda.md
- best_practices/language_guides/r.md
- best_practices/standards.md
- best_practices/teamwork.md
- best_practices/user_experience.md
- citable_software/making_software_citable.md
- nlesc_specific/e-infrastructure/das5.md
> Remove trailing whitespace

- .github/PULL_REQUEST_TEMPLATE
- README.md
- best_practices/documentation.md
- best_practices/language_guides/javascript.md
- best_practices/language_guides/python.md
- nlesc_specific/checklist/checklist_mature.md
- nlesc_specific/checklist/checklist_prerelease.md
- nlesc_specific/checklist_matrix.md
- Change master to main where needed
- Update some other outdated links
- Fix some typos
See also #246
> Change master to main where needed and update other links

- best_practices/releases.md
> Fix link to Github releases documentation.

- best_practices/checklist.md
Just a suggestion for a broken link.
> Alternative for broken link

- best_practices/language_guides/ccpp.md
> c/c++: fix a broken link

- best_practices/language_guides/opencl_cuda.md
This pull request does fix issue #299 adding the right libraries and links. The guide will be rewritten in the future, but for now this should be enough.
> Fixed issue #299

- best_practices/language_guides/ccpp.md
- best_practices/language_guides/languages_overview.md
- best_practices/language_guides/python.md
Update owners of the Python, C/C++ and Language Guides overview pages (see #252).
> update chapter owners

- best_practices/overview.md
Adds "use checklists" to the best practices chapter.
Fixes #375.
> 375 checklists

- best_practices/overview.md
> add testing to best practices chapter

- best_practices/overview.md
> add licensing to best practices chapter

- language_guides/python.md
Update the "Documentation" section of the Python Language guide
- Mention MkDocs
- Mention Markdown as an option and explain the advantages/disadvantages with respect to reStructuredText. Closes #243.
- Recommend Numpy style docstrings, as these seem the most popular in the scientific Python ecosystem, e.g. numpy, e.g. xarray, dask, scipy, matplotlib, iris, and pandas use them
> Update section on documenting Python projects

- CONTRIBUTING.md
- README.md
> improve README / front page text

- .github/workflows/link-checker-pr.yml
- .github/workflows/link-checker.yml
- language_guides/javascript.md
> fix two broken links

- index.html
This follows up on #433, cleaning up after that PR. Specifically:
- Remove commented out old code
- Before loading the Matomo plugin, check whether there's no opt-out cookie
> Matomo plugin cleanup

- CITATION.cff
- _sidebar.md
- index.html
- language_guides/rust.md
This PR adds a first iteration of a chapter about Rust to the guide. For now it just contains a very basic explanation of the main concepts of the language, a section on how to get started with the first project and some links to learning resources. I plan to add more content such as relevant projects for research and more specific topics about the language itself - but these can go in other PRs. 
Please let me know if this is in line with the guidelines.
- https://github.com/NLeSC/guide/issues/388
> first iteration of the Rust chapter

- best_practices.md
- language_guides/python.md
- technology/user_experience.md
- UX: replace with wikipedia page (HCDSociety website is offline / replaced with spam) @ctwhome 
- Best Practices links to RSQKit updated
- Python 3 tips link broken, but also no longer necessary @bouweandela
> fix broken links

- CITATION.cff
While generating a `.zenodo.json file` for the guide, I noticed cffconvert flagged some issues with CFF file, so I updated it using cffinit.
Most things on the checklist are not really applicable since this is such a small change and not really affecting the content of the guide (I think)
> Update CFF file (with cffinit) to latest version of CFF format
