languages/python.md
- If a Python code base does not contain any C-extensions (many of our projects don't), using the manylinux Docker container is overkill. Added text to explain the alternatives.
- Added the bottle web framework that I've seen used a couple of times. It's similar to flask, but a bit more light-weight for a JSON-REST service.
=> Added wheel comments and bottle web framework

software/testing.md
Removed Jenkins, as the server has been taken offline some time ago. Added polling tools links.
=> Continuous integration updates

languages/python.md
Added a link to blog post discussing differences between pip and conda.
If we agree that pip and conda are different tools and each should be used for it's own purpose, should we remove text "TODO: choose recommended approach (issue #38)", and close issue?
=> Update pip vs conda

publishing/publishing_results.md
updated publishing howto with info on including a .zenodo.json for controlling which metadata Zenodo attaches to your releases
=> how to control zenodo metadata when making releases

CONTRIBUTING.md, best_practices/language_guides/javascript.md, best_practices/language_guides/python.md
The documentation contained some links that the link checker stumbled over. With this pull request the CONTRIBUTING guidelines can be simpler. (no ``--exclude`` in the ``blc``).
=> Pull request template

citable_software/publishing_results.md
Below, describe what this Pull Request adds: Only a `www` doesn't ensure that the link is clickable, see https://guide.esciencecenter.nl/citable_software/publishing_results.html#tips-for-long-term-storage. Thus, this PR introduces the protocol prefix.
=> Hyperlink re3data.org

.travis.yml, blc-on-changed-files.sh
Run broken link checker only on the subset of files that have changed AND that are markdown files AND that are part of the GitBook. Hopefully helps to resolve the discussion [here](https://github.com/NLeSC/guide/pull/155)  and [here](https://github.com/NLeSC/guide/pull/153).
Seems to work: https://travis-ci.org/NLeSC/guide/builds/408558626
Maybe we can run the setup from [#155](https://github.com/NLeSC/guide/pull/155) in a cron job, while running this setup on PRs.
=> Blc on changed files

best_practices/code_quality.md, best_practices/documentation.md, best_practices/language_guides/java.md, best_practices/language_guides/javascript.md, best_practices/language_guides/python.md, best_practices/language_guides/r.md, best_practices/licensing.md, best_practices/releases.md, best_practices/version_control.md, nlesc_specific/e-infrastructure/e-infrastructure.md
http://blog.securem.eu/tips%20and%20tricks/2016/02/29/creating-and-publishing-a-python-module/ is broken in that the host is unknown.
In an effort to follow up on #173 this PR rephrases some sentences and replaces link texts to make them more descriptive. This means you shouldn't have to inspect the URL to understand where the link leads. In this PR I mainly focused on 'here'; there are a few other link texts that could be replaced like 'this site'.
=> Replace 'here' as link text with more meaningful text

best_practices/language_guides/java.md, best_practices/testing.md
fixed links to recetnly moved xenon repo
=> updated the xenon links 'NLeSC/Xenon' to 'xenon-middleware/xenon'

best_practices/language_guides/python.md
Mention `black` for automatically formatting Python code and remove `autopep8`, since it's less popular.
=> Mention black, remove autopep8

best_practices/language_guides/python.md
This PR adds a sentence to explain the main difference between yapf and black: configurability.
Disclaimer (which probably shows in my phrasing): I really don't like the way black splits up comma separated lines. I am all for keeping important lines as short as possible for readability. However, some parts of code are not really semantically that meaningful, like for instance long import lists, or long lists of numbers or constants or, many times, function calls with many arguments, especially those with many keyword arguments where the mapping of keywords to local variables is often trivial (i.e. `bla=bla_local`, `ding=ding_here`, etc). When black splits up these lines from say:
```python
from sqlalchemy import Column, String, Table, ForeignKey, Unicode, Boolean, Integer, BigInteger, …
```
=> Expand slightly on yapf vs black

nlesc_specific/projects/end_of_a_project.md
This PR updates `end_of_project.md` to describe the level of support (or not) which software gets once a project is completed. We also removed mentions to eStep and replaced it with links to the RSD and software sustainability protocol.
=> Description of end of project support

_sidebar.md, best_practices/language_guides/bash.md, best_practices/overview.md
Add chapter on using bash
Closes #215
=> Add chapter on using bash

User Experience/table_of_contents.md, _sidebar.md, best_practices/user_experience.md, chapter_owners.md
=> Add User Experience (UX) Section

best_practices/checklist.md
Add link to core infrastructures checklist, as recommended by http://fair-software.eu/ (basically the text is the same as we have there)
Fixes #236
=> Add link to core infrastructures checklist

best_practices/code_review.md
Add reference to reviewing jupypter notebooks with ReviewNB to Code Review section.
=> Add reference to ReviewNB to Code Review section.

best_practices/language_guides/python.md
I have gone over the full Python chapter now and made some further updates (apart from those in #259, #260, #261 and #262):
- updated documentation section to recommend sphinx only (removed pydoc)
- removed jupyterlab "under development" caveat, it's mature now
- added ReviewNB suggestion based on good experiences in a number of projects
- add some minor textual changes
=> update complete Python chapter

best_practices/code_quality.md, best_practices/documentation.md, best_practices/language_guides/python.md, best_practices/testing.md, nlesc_specific/checklist.md
This PR fixes links to the Turing Way sections about online code quality services, which were all broken due to some updates there.
For Python specifically:
- landscape.io doesn't exist anymore (at least over https)
- add Sonarcloud, which is the default choice in the python template
=> update code quality services (for Python)

best_practices/language_guides/python.md
This is a continuation and further update to 2022 of #218. To reiterate from #218:
> Primarily, I added the recommendation from the discussion in https://github.com/NLeSC/guide/issues/156. Simultaneously, I merged the two sections on Python dependencies & packages (I think the Building packages should be a subsection here, it's really intertwined). Also trimmed the existing text here and there, it was rather verbose, with lots of examples of commands that you can also easily find online with the right keywords (which we provide here).
On top of that, this PR has a few extra tweaks:
- I added a note about using Anaconda servers, as we discussed in the Software Sustainability SIG and elsewhere.
- Made `venv` the first choice instead of `virtualenv`.
- Removed all mention of `setup.py` in …
=> update python dependencies & build sections

README.md
The current DOI badge refers to version 0.9.0 on Zenodo. This PR changes the DOI to refer to all versions on Zenodo, and automatically show the latest.
=> Change DOI on README to refer to all versions

best_practices/language_guides/python.md, best_practices/version_control.md
Replaces a reference to where new projects should be registered in the chapter on version control, and updates a reference to the Noodles package from the old to the new directory in Python#Parallelisation
closes #274
=> replace nlesc.github.io software list with new RSD

.github/workflows/link-checker-pr.yml, .github/workflows/link-checker.yml, CONTRIBUTING.md, best_practices/language_guides/javascript.md, best_practices/language_guides/python.md, best_practices/testing.md, citable_software/conferences_journals_workshops.md, lychee.toml, nlesc_specific/checklist/checklist_mature.md, nlesc_specific/checklist_matrix.md, nlesc_specific/e-infrastructure/das5.md, nlesc_specific/e-infrastructure/e-infrastructure.md
- Update the link checker, because the currently used checker is deprecated.
- Fix broken links
- Only check all links for the main branch and do so every night
=> Update link checker and fix broken links

.github/workflows/link-checker-pr.yml, .github/workflows/link-checker.yml
Update the link check action because the current version issues a deprecationwarning.
> linkChecker
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Update link check action

CONTRIBUTING.md
Implementation and configuration details are necessary context for some high-level contributions. For instance, #266 about a "successful build" GH Action is not applicable in light of these details.
Fixes #266.
=> Add technical details to Contributing page

CONTRIBUTING.md, README.md
Update the main page and contribution guidelines to refer people to The Turing Way. Add a warning that many topics in the guide are outdated.
Related to #286
=> Refer people to The Turing Way

.github/workflows/link-checker-pr.yml, .github/workflows/link-checker.yml
The workflows didn't output the broken links anymore. Now they do again (I hope).
=> fix link checker output

best_practices/language_guides/python.md
Small update for the editors and IDEs. I don't think anybody uses atom, sublime or PyDev anymore, so I removed them. Added vscode.
=> update Python editors & IDEs section

best_practices/language_guides/python.md
Was trying to fix some links, but came across prospector references, so I removed those first (one of the broken links was to our prospector config file in the python-template, which no longer exists there) and added mention of Ruff.
~Will fix other links later.~
Fixed other links as well and updated some details on Conda (miniforge now includes mamba, mambaforge is discouraged).
=> Update Python chapter

lychee.toml
One of the links that failed the link-checker are a localhost reference. Links like that should never be checked and lychee has an option for that. This PR adds that option.
=> link-checker: exclude private URLs like localhost

best_practices/language_guides/python.md
I propose a fix to #290:
- recommend Github actions as default for distributing packages through pypi; update links to documentation
- suggest workflow with testpypi and manual uploads with 2FA for debugging, based on the discussion in said issue
Notes
- I have not tried out the "new" manual way with 2FA
- I removed the link to the twine tutorial as it's outdated
Questions
- signing distribution packages is not described, but it's [here]( https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ ) -- should I add something about it? 
- should the release workflow in the python template (the generated [README.dev.md](https://github.com/NLeSC/python-template/blob/main/%7B%7Bcookiecutter.directory_name%7D%7D/README.dev.md)) …
=> update on publishing through pypi

.github/PULL_REQUEST_TEMPLATE, CONTRIBUTING.md
This PR introduces some changes to the Guide's contribution guide. Open to feedback!
- The scope has been made a more explicit, not only listing what should go in, but also what shouldn't.
- We stole the Blog's idea of having an Editorial Board.
- The pull request template has been made more explicit to make sure that key points of the guidelines are not forgotten.
=> updated contributing guide + PR template

CONTRIBUTING.md
=> add style / form advice to contributing guidelines

CITATION.cff, best_practices/language_guides/python.md
fixes #326
The section on creating an installable package has been rewritten to only assume `pyproject.toml` as the relevant file to specify everything in. I've also been a bit more elaborate about what is in `pyproject.toml`, since the build system landscape is a bit more stable than it used to be when this was originally written. Speaking of build-system, I've explicitly mentioned `hatchling` and `setuptools` as our recommendations, with a link to e.g. the python packaging guide for other options.
=> rewrite installation section to use pyproject.toml

_sidebar.md, best_practices/language_guides/opencl_cuda.md
With this pull request we update and modernize the old CUDA/OpenCL page to cover more GPU programming languages and programming models. This also fixes #303 IMHO.
=> GPU Programming page

best_practices/language_guides/python.md
The standard library module with which setuptools is based has been deprecated and now removed as of Python 3.12 per [PEP 632](https://peps.python.org/pep-0632/). Additionally, virtual environments no longer contain `setuptools` nor `wheel`.
=> Update Python's best practices

_sidebar.md, best_practices/datasets.md, best_practices/language_guides/python.md
- **Remove trivial database section from Python guide**
- **Add a chapter on datasets**
This PR removes the database section from the Python guide (as
discussed in #316), and introduces a new chapter on handling datasets.
It discusses using local databases, and other data processing
libraries, and respective trade-offs.
=> Dataset chapter

CITATION.cff, best_practices/datasets.md
Fixes:
- Layout fixes in the datasets chapter that was added today (I **did** do the local preview this time that the checklist told me to do 😅).
- Added @suvayu, @f-hafner and @recap as page owners, if you all agree :)
- Added the authors of the datasets chapter to the CFF file (...again, as the checklist suggested 🫣)
Adds:
- In #316 we discussed (among many things) replacing all the Python chapter database interfaces with SQLalchemy. I now added mention of this to the databases chapter. Closes #316.
- The CFF file was not updated much for the past 5 years. I went through past closed PRs to add the author names. If people want to add their ORCID, feel free to suggest in a review comment, or simply push it to this branch.
=> Datasets quick fixes + SQLAlchemy addition + CFF updates

.github/workflows/link-checker-pr.yml
Fixes #345.
Use a different changed-files checker (the old one was no longer maintained) and also make the link checking more fine-grained by only checking added lines for broken links.
We now use a matrix to parallelize over changed files. This slows down the complete workflow a bit in some cases, but it does offer a nicer user experience, because the files that are checked will now be shown in the GitHub UI itself, instead of only in the workflow run logs.
Lychee is installed directly from the GitHub nightly release. This is really fast. The original reason, though, was because there is no Ubuntu package for Lychee. Works out well, though.
Determining the base SHA is a bit convoluted, because GitHub does not provide this in a usable way. See …
=> update PR link checker workflow

CONTRIBUTING.md, README.md, best_practices/code_quality.md, best_practices/documentation.md, best_practices/overview.md, language_guides/python.md, language_guides/r.md
* Replace the old links to The Turing Way (`https://the-turing-way.netlify.app`) with the new URL (`https://book.the-turing-way.org`)
* Fix two broken links to the language guides (which were broken by the move of the language guide in #340)
Closes #342
=> 342 turing way url

best_practices/code_quality.md, index.html, language_guides/javascript.md
This is a small update for the JavaScript/TypeScript chapter, focusing on Javascript runtimes. This is part of working towards closing #268.
* update the information on JavaScript runtimes
* add `https:` to linked dependencies
* fix a double `/` in a URL introduced in #352
Related to #268
=> improve documentation on JS runtimes

.github/workflows/link-checker.yml, best_practices/releases.md, language_guides/ccpp.md, language_guides/python.md
This PR:
- Updates checkout action to version 4
- Updates the lychee action to version 2
- Makes lychee accept status 429 (too many requests) as a successful check. This makes some sense: a 429 may very well be a live link, just one that currently you are not allowed to view. If it were a broken link, the server should return 404 instead. I'm not 100% sure if all webservers work this way (i.e. if they first check for 404 and only then apply throttling to give 429), but in any case it seems the best we can do, because we cannot otherwise control request rate from GitHub Actions, as far as I know.
- Adds a manual run trigger to the link checker
- Removes the workflow part where we only fail if there are 10 or more broken links. I think we can get to 0 broken links by using lychee options, …
=> [CI] update link checker and handle status 429 (too many requests)

language_guides/javascript.md
This PR focuses mostly on JS frameworks and IDEs. I expect one more PR after this before issue #268 can be closed.
=> improvements on frameworks and IDEs

language_guides/ccpp.md
Fixed broken link in C/C++ chapter on HDF5 which moved from Bitbucket to GitHub (already in 2020... amazing that it didn't break earlier).
=> fix broken link in C/C++ chapter

language_guides/javascript.md
This PR focuses on the introduction, debugging, testing and code style sections, together with some other small changes, of the JS chapter. Although improvements can always be made, I feel like this PR closes #268.
=> changes on debuggers, testing, code style and more

.github/dependabot.yml
Set up [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) to automatically check for updates to GitHub Actions and open a pull request if necessary.
=> Use dependabot to automatically keep GitHub Actions up to date

.github/workflows/link-checker-pr.yml, .github/workflows/link-checker.yml, best_practices/overview.md
=> add version control to Best Practices chapter

language_guides/python.md
Added a subsection on type hints, following the discussion in #310. Also added a few cool libraries, e.g. FastAPI that was mentioned by Bouwe in #54 and Typer from the same author.
Fixes #310.
=> add Python type hints

best_practices/overview.md
=> Add pointer to SMP chapter

CITATION.cff, language_guides/r.md
The `R` language kept evolving since we wrote this. It needs some updates
=> Update R chapter

.github/workflows/link-checker-pr.yml, .github/workflows/link-checker.yml, technology/gpu.md
Ignores Posit documentation URLs from CI (they seem to get blocked from GitHub CI) and updates some outdated links in the GPU chapter.
Fixes #358.
Fixes #355.
=> Fix broken links

language_guides/fortran.md
The domain fortran90.org is down. Luckily, the sources of this website are on GitHub, so we just link there now.
=> replace fortran90.org with markdown sources on github

.github/workflows/link-checker-pr.yml, index.html, privacy.md
Fixes #421
Adds track navigation changes to matomo and
adds the opting out from matomo tracking on privacy page.
It also drops the remnant of Google Analytics.
=> Track page views

index.html
This is another stab at fixing #421 (previous try in #432). This time, we try to use the "official" (though undocumented) Matomo plugin, copy-pasted here because we need an adaptation: the disableCookies option. Also, we need to check whether this works at all, because the official plugin is pretty old (5 years) and also it seems to have the same problem as our previous implementation (see https://github.com/NLeSC/guide/issues/421#issuecomment-2782462053), i.e. it uses `hook.beforeEach`.
=> use the matomo plugin, but customized

.github/workflows/pdf.yml
Updated the Generate PDF GitHub action to use the `--no-sandbox` for chromium, as explained in https://github.com/kernoeb/docker-docsify-pdf/issues/13. 
This should fix https://github.com/NLeSC/guide/issues/270#issuecomment-2778113525.
Note: We are using the `main` tag and not latest, because they did not make a release since they introduced `--no-sandbox`.
I tested the updated GitHub Action [here](https://github.com/NLeSC/guide/actions/runs/14710221587).
=> Fix the error that prevented generating the PDF guide on release
